parameters:
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
    paypal_client_id: '%env(PAYPAL_CLIENT_ID)%'
    paypal_client_secret: '%env(PAYPAL_CLIENT_SECRET)%'
    paypal_mode: '%env(PAYPAL_MODE)%'
    app.frontend_url: '%env(resolve:FRONTEND_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $senderEmail: '%env(MAIL_SENDER_ADDRESS)%'
            $senderName: '%env(MAIL_SENDER_NAME)%'
            $adminEmail: '%env(MAIL_ADMIN_RECEIVER)%'

    App\:
        resource: '../src/'

    # CONFIGURATION MONDIAL RELAY
    App\Service\MondialRelayService:
        arguments:
            $mrEnseigne: '%env(MONDIAL_RELAY_ENSEIGNE)%'
            $mrPrivateKey: '%env(MONDIAL_RELAY_PRIVATE_KEY)%'
            $mrActionCode: '%env(MONDIAL_RELAY_ACTION_CODE)%'

    App\Service\ColissimoService:
        arguments:
            $colissimoApiKey: '%env(COLISSIMO_API_KEY)%'